=== metarex-media/mrx-tool/encode/jsonschema/manifest_Schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "MRX Manifest Schema",
    "description": "The Schema for the MRX Manifest schema, version 0.0.0.1",
    "type": "object",
    "properties": {
        "UMID": {
            "type": "string",
            "description": "The UMID of the MRX file the manifest is attached to"
        },
        "Mrx Manifest Version": {
            "type": "string"
        },
        "MRXTool": {
            "type": "string"
        },
        "Data Streams": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/Partition"
            },
            "description": "The coordiantes of the location to be added, a->p is the x axis, 0->9 are the allowed y axis parameters. Alternativley an alias can be used if already declared"
        },
        "History": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/History"
            },
            "description": "The coordiantes of the location to be added, a->p is the x axis, 0->9 are the allowed y axis parameters. Alternativley an alias can be used if already declared"
        }
    },
    "required": [
        "UMID"
    ],
    "additionalProperties": false,
    "$defs": {
        "Partition": {
            "properties": {
                "Common Data Properties": {
                    "type": "object",
                    "properties": {
                        "test": {
                            "type": "string"
                        }
                    }
                },
                "Essence": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/FileLayout"
                    }
                }
            }
        },
        "FileLayout": {
            "properties": {
                "Hash": {
                    "type": "string",
                    "length": 64,
                    "description": "The sha 256 of the data"
                },
                "DataOrigin": {
                    "type": "string"
                },
                "EditDate": {
                    "type": "string"
                },
                "Custom Meta Data": {
                    "type": "object"
                }
            },
            "required": [
                "Hash"
            ],
            "additionalProperties": false
        },
        "History": {
            "properties": {
                "Mrx Manifest Version": {
                    "type": "string"
                },
                "MRXTool": {
                    "type": "string"
                },
                "UMID": {
                    "type": "string",
                    "description": "The UMID of the MRX file the manifest is attached to"
                },
                "Data Streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/Partition"
                    },
                    "description": "The coordiantes of the location to be added, a->p is the x axis, 0->9 are the allowed y axis parameters. Alternativley an alias can be used if already declared"
                },
                "SnapShot Date": {
                    "type": "string"
                }
            },
            "required": [
                "UMID",
                "SnapShot Date"
            ],
            "additionalProperties": false
        }
    }
}

=== metarex-media/mrx-tool/testdata/manifest_prev.json
{
    "UMID": "060a2b340101010501010c2013e4173480bfd43cb56a484b914241cbf910694b",
    "Mrx Manifest Version": "0.0.0.1",
    "MRXTool": "Mr MXF's MRX golang command line tool",
    "Data Streams": [
        {
            "Common Data Properties": {
                "StreamID": 1,
                "StreamType": "Text based frame data"
            },
            "Essence": [
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0000frameText",
                    "EditDate": "2023-06-15 14:14:15.4862202 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0001frameText",
                    "EditDate": "2023-06-15 14:14:15.486741 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0002frameText",
                    "EditDate": "2023-06-15 14:14:15.4872616 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0003frameText",
                    "EditDate": "2023-06-15 14:14:15.4875006 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0004frameText",
                    "EditDate": "2023-06-15 14:14:15.4880782 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0005frameText",
                    "EditDate": "2023-06-15 14:14:15.4885815 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0006frameText",
                    "EditDate": "2023-06-15 14:14:15.4890973 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0007frameText",
                    "EditDate": "2023-06-15 14:14:15.4896173 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0008frameText",
                    "EditDate": "2023-06-15 14:14:15.4901473 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0009frameText",
                    "EditDate": "2023-06-15 14:14:15.4906692 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0010frameText",
                    "EditDate": "2023-06-15 14:14:15.4912459 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0011frameText",
                    "EditDate": "2023-06-15 14:14:15.4917531 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0012frameText",
                    "EditDate": "2023-06-15 14:14:15.4922693 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0013frameText",
                    "EditDate": "2023-06-15 14:14:15.4934596 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0014frameText",
                    "EditDate": "2023-06-15 14:14:15.4945428 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0015frameText",
                    "EditDate": "2023-06-15 14:14:15.4952923 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0016frameText",
                    "EditDate": "2023-06-15 14:14:15.4963219 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0017frameText",
                    "EditDate": "2023-06-15 14:14:15.4979807 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0018frameText",
                    "EditDate": "2023-06-15 14:14:15.4979807 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0019frameText",
                    "EditDate": "2023-06-15 14:14:15.4990466 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0020frameText",
                    "EditDate": "2023-06-15 14:14:15.4990466 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0021frameText",
                    "EditDate": "2023-06-15 14:14:15.4995704 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0022frameText",
                    "EditDate": "2023-06-15 14:14:15.5000871 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0023frameText",
                    "EditDate": "2023-06-15 14:14:15.5006201 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0024frameText",
                    "EditDate": "2023-06-15 14:14:15.5017256 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0025frameText",
                    "EditDate": "2023-06-15 14:14:15.5022577 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0026frameText",
                    "EditDate": "2023-06-15 14:14:15.5027837 +0100 BST"
                },
                {
                    "Hash": "db9da06cb619f3884d533c9e6cfd9bf8335f19f34bdbd948d2b4bc67e8dbe945",
                    "DataOrigin": "C:\\Users\\mmTri\\Documents\\Gitlab\\mrx-parser\\encode\\testdata\\testbase\\0001mrxip\\0027frameText",
                    "EditDate": "2023-06-15 14:14:15.5033131 +0100 BST"
